version: "3"

services:
  db:
    image: postgres:latest
    restart: on-failure
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: exchange
      POSTGRES_DB: exchange
    volumes:
        - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
    db_data:
