// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/jorgejr568/exchange-register-go/internal/exchange/entity (interfaces: SyncExchangeRateUseCase,ListExchangesUseCase,ExchangeService)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_use_case.go -package=mocks github.com/jorgejr568/exchange-register-go/internal/exchange/entity SyncExchangeRateUseCase,ListExchangesUseCase,ExchangeService
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	entity "github.com/jorgejr568/exchange-register-go/internal/exchange/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockSyncExchangeRateUseCase is a mock of SyncExchangeRateUseCase interface.
type MockSyncExchangeRateUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockSyncExchangeRateUseCaseMockRecorder
	isgomock struct{}
}

// MockSyncExchangeRateUseCaseMockRecorder is the mock recorder for MockSyncExchangeRateUseCase.
type MockSyncExchangeRateUseCaseMockRecorder struct {
	mock *MockSyncExchangeRateUseCase
}

// NewMockSyncExchangeRateUseCase creates a new mock instance.
func NewMockSyncExchangeRateUseCase(ctrl *gomock.Controller) *MockSyncExchangeRateUseCase {
	mock := &MockSyncExchangeRateUseCase{ctrl: ctrl}
	mock.recorder = &MockSyncExchangeRateUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSyncExchangeRateUseCase) EXPECT() *MockSyncExchangeRateUseCaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockSyncExchangeRateUseCase) Execute(ctx context.Context, req entity.SyncExchangeRateRequest) (*entity.SyncExchangeRateResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, req)
	ret0, _ := ret[0].(*entity.SyncExchangeRateResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockSyncExchangeRateUseCaseMockRecorder) Execute(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockSyncExchangeRateUseCase)(nil).Execute), ctx, req)
}

// MockListExchangesUseCase is a mock of ListExchangesUseCase interface.
type MockListExchangesUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockListExchangesUseCaseMockRecorder
	isgomock struct{}
}

// MockListExchangesUseCaseMockRecorder is the mock recorder for MockListExchangesUseCase.
type MockListExchangesUseCaseMockRecorder struct {
	mock *MockListExchangesUseCase
}

// NewMockListExchangesUseCase creates a new mock instance.
func NewMockListExchangesUseCase(ctrl *gomock.Controller) *MockListExchangesUseCase {
	mock := &MockListExchangesUseCase{ctrl: ctrl}
	mock.recorder = &MockListExchangesUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockListExchangesUseCase) EXPECT() *MockListExchangesUseCaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockListExchangesUseCase) Execute(ctx context.Context, req entity.ListExchangesRequest) (*entity.ListExchangesResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, req)
	ret0, _ := ret[0].(*entity.ListExchangesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockListExchangesUseCaseMockRecorder) Execute(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockListExchangesUseCase)(nil).Execute), ctx, req)
}

// MockExchangeService is a mock of ExchangeService interface.
type MockExchangeService struct {
	ctrl     *gomock.Controller
	recorder *MockExchangeServiceMockRecorder
	isgomock struct{}
}

// MockExchangeServiceMockRecorder is the mock recorder for MockExchangeService.
type MockExchangeServiceMockRecorder struct {
	mock *MockExchangeService
}

// NewMockExchangeService creates a new mock instance.
func NewMockExchangeService(ctrl *gomock.Controller) *MockExchangeService {
	mock := &MockExchangeService{ctrl: ctrl}
	mock.recorder = &MockExchangeServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockExchangeService) EXPECT() *MockExchangeServiceMockRecorder {
	return m.recorder
}

// ListExchanges mocks base method.
func (m *MockExchangeService) ListExchanges(ctx context.Context, sourceCurrency, targetCurrency string) ([]entity.Exchange, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListExchanges", ctx, sourceCurrency, targetCurrency)
	ret0, _ := ret[0].([]entity.Exchange)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListExchanges indicates an expected call of ListExchanges.
func (mr *MockExchangeServiceMockRecorder) ListExchanges(ctx, sourceCurrency, targetCurrency any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListExchanges", reflect.TypeOf((*MockExchangeService)(nil).ListExchanges), ctx, sourceCurrency, targetCurrency)
}

// ReceiveExchangeRate mocks base method.
func (m *MockExchangeService) ReceiveExchangeRate(ctx context.Context, sourceCurrency, targetCurrency string, rate float64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReceiveExchangeRate", ctx, sourceCurrency, targetCurrency, rate)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReceiveExchangeRate indicates an expected call of ReceiveExchangeRate.
func (mr *MockExchangeServiceMockRecorder) ReceiveExchangeRate(ctx, sourceCurrency, targetCurrency, rate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReceiveExchangeRate", reflect.TypeOf((*MockExchangeService)(nil).ReceiveExchangeRate), ctx, sourceCurrency, targetCurrency, rate)
}
